# ===== PRO =====

# --- /home/ansible_usr/PRO/PRO_BONO_CAPAS_WEB/inventory ---
[bono-capas-web-netglobalis1]
im-bono3-web08-ng1
im-bono3-web09-ng1
im-bono3-web04-ng1
im-bono3-web05-ng1
im-bono3-web06-ng1
im-bono3-web07-ng1
im-bono3-web10-ng1
im-bono3-web01-ng1 ansible_user=ansible_usr
im-bono3-web02-ng1
im-bono3-web03-ng1
im-bono3-web11-ng1
im-bono3-web12-ng1
im-bono3-web13-ng1
im-bono3-web14-ng1
im-bono3-cron01-ng1
[bono-capas-web-netglobalis1:vars]
ansible_user=ansible
ansible_port=14225

[bono-capas-web-iia1]
im-bono3-web01-iia1
im-bono3-web02-iia1
im-bono3-web03-iia1
im-bono3-web04-iia1
im-bono3-web05-iia1
im-bono3-web06-iia1
im-bono3-web07-iia1
im-bono3-web08-iia1
im-bono3-web09-iia1
im-bono3-web10-iia1
im-bono3-web11-iia1
im-bono3-web12-iia1
im-bono3-web13-iia1
im-bono3-web14-iia1
im-bono3-web15-iia1
[bono-capas-web-iia1:vars]
ansible_user=ansible
ansible_port=14225

# --- /home/ansible_usr/PRO/PRO_CAPAS_WEB_LIQUIDADOR/inventory ---
[capas-web-liquidador-ng]
im-liquidador-web01-ng1
im-liquidador-web02-ng1
im-liquidador-web03-ng1
im-liquidador-web04-ng1
im-liquidador-web05-ng1 ansible_user=ansible
[capas-web-liquidador-ng:vars]
ansible_port=14225

[capas-web-liquidador-iia]
im-liquidador-web01-iia1
im-liquidador-web02-iia1
im-liquidador-web03-iia1
im-liquidador-web04-iia1
[capas-web-liquidador-iia:vars]
ansible_port=14225


# --- /home/ansible_usr/PRO/PRO_IM_BONO3/inventory ---
[im-bono3]
im-bono3-dns03-ng1
im-bono3-sproxy01-ng1
im-bono3-ca01-ng1
im-bono3-reporte01-ng1
im-bono3-reporte02-ng1
im-bono3-ng2
im-bono3-IIA1
im-bono3-IIA3
im-bono3-sproxy01-iia1
im-reportesmysql-iia1
im-bono3-percona02-iia1
im-bono3-perconaupgrade01-ng1
[im-bono3:vars]
ansible_port=14225

[im-bono3-motor]
im-bono3-motor01-ng1
im-bono3-motor02-ng1
#im-bono3-motor-fonasa-ng1
im-bono3-motor01-iia1
im-bono3-motor02-iia1
[im-bono3-motor:vars]
ansible_port=14225

[im-bono3-md]	
im-bono3-md01-ng1
im-bono3-md02-ng1
im-bono3-md03-ng1
im-bono3-md01-iia1
im-bono3-md02-iia1
im-bono3-md03-iia1
[im-bono3-md:vars]
ansible_port=14225

# --- /home/ansible_usr/PRO/PRO_IM_CME3/inventory ---
[im-cme3-ng]
im-cme3-ca01-ng1.txel.systems
im-cme3-ha01-ng1.txel.systems
#im-cme3-percona01-ng1
im-cme3-ha02-ng1 
[im-cme3-ng:vars]
ansible_port=14225

[im-cme3-iia]
im-cme3-percona01-iia1
im-cme3-ca01-iia1
im-cme3-ha01-iia1
im-cme3-ha02-iia1 
[im-cme3-iia:vars]
ansible_port=14225

[im-cme3-web-ng]
im-cme3-web01-ng1.txel.systems
im-cme3-web02-ng1.txel.systems
im-cme3-web03-ng1
im-cme3-web04-ng1
im-cme3-web05-ng1
[im-cme3-web-ng:vars]
ansible_user=ansible
ansible_port=14225

[im-cme3-web-iia]
im-cme3-web01-iia1
im-cme3-web02-iia1
im-cme3-web03-iia1
[im-cme3-web-iia:vars]
ansible_user=ansible
ansible_port=14225

[im-cme3-md]
im-cme3-md01-ng1.txel.systems
im-cme3-md01-iia1
[im-cme3-md:vars]
ansible_user=ansible_usr
ansible_port=14225

# --- /home/ansible_usr/PRO/PRO_IM_DEC5/inventory ---
[im-dec5-iia]
im-dec5-app01-iia1
im-dec5-percona01-iia1
im-dec5-web01-iia1
im-dec5-web02-iia1
im-dec-doc01-iia1
im-dec-nfs01-iia1
im-dec5-ha01-iia1
poc-im-dec5-percona01-iia1
[im-dec5-iia:vars]
ansible_port=14225

[im-dec5-ng]
im-dec-doc02-ng1
im-dec-haproxy02-ng1
im-dec5-app02-ng1
im-dec5-elastic02-ng1 
im-dec5-mail02-ng1
im-dec5-percona02-ng1 
im-dec5-percona03-ng1
im-dec5-web01-ng1
im-dec5-web02-ng1
[im-dec5-ng:vars]
ansible_port=14225

# --- /home/ansible_usr/PRO/PRO_IM_LME/inventory ---
[im-lme-web]
im-lme-web01-ng1 ansible_user=ansible
im-lme-web02-ng1 ansible_user=ansible
im-lme-web03-ng1 ansible_user=ansible
im-lme-web04-ng1 ansible_user=ansible
im-lme-web05-ng1 ansible_user=ansible
im-lme-web01-iia1 ansible_user=ansible
im-lme-web02-iia1 ansible_user=ansible
im-lme-web03-iia1 ansible_user=ansible
im-lme-web04-iia1 ansible_user=ansible

[im-lme-web-php8-ng1]
im-lme-web01-php8imed-ng1
im-lme-web02-php8imed-ng1
im-lme-web03-php8imed-ng1
im-lme-web04-php8imed-ng1
im-lme-web05-php8imed-ng1

[im-lme-web-php8-iia1]
im-lme-web01-php8imed-iia1
im-lme-web02-php8imed-iia1
im-lme-web03-php8imed-iia1
im-lme-web04-php8imed-iia1
im-lme-web05-php8imed-iia1

[im-lme-ha]
im-lme-ha01-ng1
im-lme-ha01-iia1
im-lme-ha01-php8imed-iia1

[im-lme-percona]
#im-lme-percona01-ng1 #2024-05-30 Servidor apagado por no uso. Confirmado por Gandhi Carrasco.
im-lme-percona01-ng2
im-lme-percona01-iia1
im-lmebd-iia2
im-lmebd-iia1

[im-lme-mysql8-bd]
im-lmemysql8-ng1
im-lmemysql8-iia1
im-lmemysql8-iia2


[im-lme-ws]
im-lme-ws01-ng1
im-lme-ws02-ng1
im-lme-ws01-iia1

[im-lme-mysql8]
#im-lme-ha01-mysql8-iia1
#im-lme-web02-mysql8-iia1
#im-lme-ws01-mysql8-iia1
im-lme-rancher-master-mysql8-iia1
im-lme-mysql8router01-ng1
im-lme-mysql8router01-iia1


[im-lme:children]
im-lme-web
im-lme-web-php8-ng1
im-lme-web-php8-iia1
im-lme-ha
im-lme-percona
im-lme-ws
im-lme-mysql8
im-lme-mysql8-bd
[im-lme:vars]
ansible_port=14225

# --- /home/ansible_usr/PRO/PRO_IM_RME/inventory ---
[im-rme]
#im-rme-ha01-ng1.txel.systems
#im-rme-web01-ng1.txel.systems
#im-rme-ha01-iia1
#im-rme-web01-iia1
[im-rme:vars]
ansible_port=14225

# --- /home/ansible_usr/PRO/PRO_OTROS/inventory ---
[otros]
im-liquidador-ha01-ng1
#im-liquidador-percona01-ng1
im-liquidador-percona01-iia1
im-dbs03-ng1
#au-nasaudit-iia ansible_port=22 # 2024-03-28 Se apaga servidor para posterior baja. Se conservará para análisis de levantamiento, en el marco de requerimiento de los chamos para nuevo servidor nfs.
#im-nasfelec-ng1 ansible_user=root # 2026-04-09 Se comenta check ya que al ser appliance no trae metricas.
im-pentaho-ng1
im-monetdb01-ng1
im-medsign-mongo01-gcp1-iia1
im-medsign-mongo01pre-gcp1-iia1
poc-im-medsign-mongo01-gcp1-iia1
im-liquidador-redis01-ng1
im-liquidador-ha01-iia1
im-liquidador-ha02-ng1
im-sftp-mongo01-iia1
im-sftp-klap-ng1 ansible_port=22
[otros:vars]
ansible_port=14225

[qbiz]
im-qbiz-hub01-iia1
im-qbiz-netsuite01-iia1
[qbiz:vars]
ansible_port=14225


# ===== QA =====
[qa-ng]
im-bono3qa-web02-ng1
im-bono3qa-sproxy01-ng1
im-lmeqa-percona02-ng1
im-rmeqa-percona01-ng1
im-rmeqa-web01-ng1
im-lmeqa-web02-ng1
im-lmeqa-web03-ng1
im-bono3qa-web04-ng1
im-bono3qa-percona02-ng1
im-bono3qa-ha01-ng1
im-mysqlrouterqa01-ng1
im-bono3qa-ha02-ng1
im-bono3qa-ha03-ng1
im-bono3qa-md02-ng1
im-bono3qa-web03-ng1
im-bono3qa-motor03-ng1
im-bono3qa-sproxy02-ng1
im-bono3qa-reporteria01-ng1
im-bono3qa-ha05-ng1	
im-bono3qa-web05-ng1
[qa-ng:vars]
ansible_port=14225

[qa-lme-php8]
im-lmeqa-ha01-ng1
im-lmeqa-web01-php8imed-ng1
im-lmeqa-web02-php8imed-ng1
im-lmeqa-web03-php8imed-ng1
im-lmeqa-web04-php8imed-ng1
im-lmeqa-web05-php8imed-ng1
im-lmeqa-web06-php8imed-ng1
[qa-lme-php8:vars]
ansible_port=14225

[qa-bono-php8]
im-bono3qa-ha04-ng1
im-bono3qa-web01-php8imed-ng1
[qa-bono-php8:vars]
ansible_port=14225

[qa-iia]
im-bono3qa-api01-iia1
im-bono3qa-ha01-iia1
im-bono3qa-ha02-iia1
im-bono3qa-md01-iia1
im-bono3qa-motor01-iia1
im-bono3qa-percona01-iia1
#im-bono3qa-reporteria02-iia1 # 2024-xx-xx Servidor apagado a solicitud de Fabio Araque.
im-bono3qa-reporteria03-iia1
im-bono3qa-web01-iia1
im-cme3qa-ca01-iia1
im-cme3qa-md01-iia1
im-cme3qa-percona01-iia1
im-cme3qa-web01-iia1
im-liquidadorqa-elastic01-iia1
im-liquidadorqa-logger01-iia1
im-liquidadorqa-percona01-iia1
im-liquidadorqa-web01-iia1
im-lmeqa-ha01-iia1
im-lmeqa-percona01-iia1
im-lmeqa-web01-iia1
im-mgpsqa-web01-iia1
im-rmeqa-percona01-iia1
im-rmeqa-web01-iia1
[qa-iia:vars]
ansible_port=14225

[qa-dec5]
im-qa-dec5-app01-ng1
im-qa-dec5-elastic01-ng1
im-qa-dec5-mail01-ng1
im-qa-dec5-percona01-ng1
im-qa-dec5-web01-ng1
im-qa-dec-doc02-ng1
[qa-dec5:vars]
ansible_port=14225




# ===== DEV =====
[ambiente-dev]
im-bono3dev-web01-ng1
im-dev-liquidador-web01-ng1
im-dev-liquidador-percona01-ng1
im-bono3dev-percona02-ng1
[ambiente-dev:vars]
ansible_port=14225

[ambiente-dec5]
im-dev-dec-doc02-ng1
im-dev-dec5-app01-ng1
im-dev-dec5-elastic01-ng1
im-dev-dec5-mail01-ng1
im-dev-dec5-percona01-ng1
im-dev-dec5-web01-ng1
[ambiente-dec5:vars]
ansible_port=14225


[dev:children]
ambiente-dev

[qa:children]
qa-ng
qa-iia
qa-dec5
qa-bono-php8
qa-lme-php8

[pro:children]
im-bono3
im-cme3-ng
im-cme3-iia
im-cme3-md
im-cme3-web-ng
im-cme3-web-iia
im-dec5-ng
im-dec5-iia
im-lme
qbiz
capas-web-liquidador-ng
capas-web-liquidador-iia
bono-capas-web-iia1
bono-capas-web-netglobalis1
