[all]
Pivote ansible_port=14225
Prometheus-grafana ansible_port=22
clon-im-bono3-cob-ha01-ng1 ansible_port=14225
im-ansible02-ng1 ansible_port=14225
im-bono3-IIA1 ansible_port=14225
im-bono3-IIA3 ansible_port=14225
im-bono3-ca01-ng1 ansible_port=14225
im-bono3-cron01-ng1 ansible_port=14225 ansible_user=ansible
im-bono3-dns01-iia1 ansible_port=14225
im-bono3-dns01-ng1 ansible_port=14225
im-bono3-dns03-ng1 ansible_port=14225
im-bono3-ha03-ng1 ansible_port=14225
im-bono3-habupa01-ng1 ansible_port=14225
im-bono3-md01-iia1 ansible_port=14225
im-bono3-md01-ng1 ansible_port=14225
im-bono3-md02-iia1 ansible_port=14225
im-bono3-md02-ng1 ansible_port=14225
im-bono3-md03-iia1 ansible_port=14225
im-bono3-md03-ng1 ansible_port=14225
im-bono3-motor01-iia1 ansible_port=14225
im-bono3-motor01-ng1 ansible_port=14225
im-bono3-motor02-iia1 ansible_port=14225
im-bono3-motor02-ng1 ansible_port=14225
im-bono3-ng2 ansible_port=14225
im-bono3-percona02-iia1 ansible_port=14225
im-bono3-perconaupgrade01-ng1 ansible_port=14225
im-bono3-rancher01-iia1 ansible_port=14225
im-bono3-reporte01-ng1 ansible_port=14225
im-bono3-reporte02-ng1 ansible_port=14225
im-bono3-sproxy01-iia1 ansible_port=14225
im-bono3-sproxy01-ng1 ansible_port=14225
im-bono3-web01-iia1 ansible_port=14225
im-bono3-web01-ng1 ansible_port=14225 ansible_user=ansible_usr
im-bono3-web02-iia1 ansible_port=14225
im-bono3-web02-ng1 ansible_port=14225
im-bono3-web03-iia1 ansible_port=14225
im-bono3-web03-ng1 ansible_port=14225
im-bono3-web04-iia1 ansible_port=14225
im-bono3-web04-ng1 ansible_port=14225
im-bono3-web05-iia1 ansible_port=14225
im-bono3-web05-ng1 ansible_port=14225
im-bono3-web06-iia1 ansible_port=14225
im-bono3-web06-ng1 ansible_port=14225
im-bono3-web07-iia1 ansible_port=14225
im-bono3-web07-ng1 ansible_port=14225
im-bono3-web08-iia1 ansible_port=14225
im-bono3-web08-ng1 ansible_port=14225
im-bono3-web09-iia1 ansible_port=14225
im-bono3-web09-ng1 ansible_port=14225
im-bono3-web10-iia1 ansible_port=14225
im-bono3-web10-ng1 ansible_port=14225
im-bono3-web11-iia1 ansible_port=14225
im-bono3-web11-ng1 ansible_port=14225
im-bono3-web12-iia1 ansible_port=14225
im-bono3-web12-ng1 ansible_port=14225
im-bono3-web13-iia1 ansible_port=14225
im-bono3-web13-ng1 ansible_port=14225
im-bono3-web14-iia1 ansible_port=14225
im-bono3-web14-ng1 ansible_port=14225
im-bono3-web15-iia1 ansible_port=14225
im-bono3dev-percona02-ng1 ansible_port=14225
im-bono3dev-web01-ng1 ansible_port=14225
im-bono3pre-ca01-ng1 ansible_port=14225
im-bono3pre-ha01-ng1 ansible_port=14225
im-bono3pre-ha01-php8imed-iia1 ansible_port=14225
im-bono3pre-ha02-ng1 ansible_port=14225
im-bono3pre-md01-ng1 ansible_port=14225
im-bono3pre-md02-ng1 ansible_port=14225
im-bono3pre-motor01-ng1 ansible_port=14225
im-bono3pre-motor02-ng1 ansible_port=14225
im-bono3pre-percona01-ng1 ansible_port=14225
im-bono3pre-percona02-ng1 ansible_port=14225
im-bono3pre-percona03-ng1 ansible_port=14225
im-bono3pre-percona03-ng2 ansible_port=14225
im-bono3pre-percona04-ng1 ansible_port=14225
im-bono3pre-redis01-ng1 ansible_port=14225
im-bono3pre-reporte01-ng1 ansible_port=14225
im-bono3pre-sproxy01-ng1 ansible_port=14225
im-bono3pre-web01-ng1 ansible_port=14225 ansible_user=ansible
im-bono3pre-web01-php8imed-iia1 ansible_port=14225
im-bono3pre-web02-ng1 ansible_port=14225 ansible_user=ansible
im-bono3pre-web03-ng1 ansible_port=14225 ansible_user=ansible
im-bono3pre-web04-ng1 ansible_port=14225 ansible_user=ansible
im-bono3pre-web05-ng1 ansible_port=14225 ansible_user=ansible
im-bono3qa-api01-iia1 ansible_port=14225
im-bono3qa-ha01-iia1 ansible_port=14225
im-bono3qa-ha01-ng1 ansible_port=14225
im-bono3qa-ha02-iia1 ansible_port=14225
im-bono3qa-ha02-ng1 ansible_port=14225
im-bono3qa-ha03-ng1 ansible_port=14225
im-bono3qa-ha04-ng1 ansible_port=14225
im-bono3qa-ha05-ng1 ansible_port=14225
im-bono3qa-md01-iia1 ansible_port=14225
im-bono3qa-md02-ng1 ansible_port=14225
im-bono3qa-motor01-iia1 ansible_port=14225
im-bono3qa-motor03-ng1 ansible_port=14225
im-bono3qa-percona01-iia1 ansible_port=14225
im-bono3qa-percona02-ng1 ansible_port=14225
im-bono3qa-reporteria01-ng1 ansible_port=14225
im-bono3qa-reporteria03-iia1 ansible_port=14225
im-bono3qa-sproxy01-ng1 ansible_port=14225
im-bono3qa-sproxy02-ng1 ansible_port=14225
im-bono3qa-web01-iia1 ansible_port=14225
im-bono3qa-web01-php8imed-ng1 ansible_port=14225
im-bono3qa-web02-ng1 ansible_port=14225
im-bono3qa-web03-ng1 ansible_port=14225
im-bono3qa-web04-ng1 ansible_port=14225
im-bono3qa-web05-ng1 ansible_port=14225
im-cdcdeploy01-ng1 ansible_port=14225
im-cme3-ca01-iia1 ansible_port=14225
im-cme3-ca01-ng1.txel.systems ansible_port=14225
im-cme3-ha01-iia1 ansible_port=14225
im-cme3-ha01-ng1.txel.systems ansible_port=14225
im-cme3-ha02-iia1 ansible_port=14225
im-cme3-ha02-ng1 ansible_port=14225
im-cme3-md01-iia1 ansible_port=14225
im-cme3-md01-ng1.txel.systems ansible_port=14225
im-cme3-percona01-iia1 ansible_port=14225
im-cme3-web01-iia1 ansible_port=14225
im-cme3-web01-ng1.txel.systems ansible_port=14225
im-cme3-web02-iia1 ansible_port=14225
im-cme3-web02-ng1.txel.systems ansible_port=14225
im-cme3-web03-iia1 ansible_port=14225
im-cme3-web03-ng1 ansible_port=14225
im-cme3-web04-ng1 ansible_port=14225
im-cme3-web05-ng1 ansible_port=14225
im-cme3pre-ca01-ng1 ansible_port=14225
im-cme3pre-md01-ng1 ansible_port=14225
im-cme3pre-percona01-ng1 ansible_port=14225
im-cme3pre-web01-ng1 ansible_port=14225
im-cme3qa-ca01-iia1 ansible_port=14225
im-cme3qa-md01-iia1 ansible_port=14225
im-cme3qa-percona01-iia1 ansible_port=14225
im-cme3qa-web01-iia1 ansible_port=14225
im-contingencia-ha01-ng1 ansible_port=22
im-dbs03-ng1 ansible_port=14225
im-dec-doc01-iia1 ansible_port=14225
im-dec-doc02-ng1 ansible_port=14225
im-dec-haproxy02-ng1 ansible_port=14225
im-dec-nfs01-iia1 ansible_port=14225
im-dec5-app01-iia1 ansible_port=14225
im-dec5-app02-ng1 ansible_port=14225
im-dec5-elastic02-ng1 ansible_port=14225
im-dec5-ha01-iia1 ansible_port=14225
im-dec5-mail02-ng1 ansible_port=14225
im-dec5-percona01-iia1 ansible_port=14225
im-dec5-percona02-ng1 ansible_port=14225
im-dec5-percona03-ng1 ansible_port=14225
im-dec5-web01-iia1 ansible_port=14225
im-dec5-web01-ng1 ansible_port=14225
im-dec5-web02-iia1 ansible_port=14225
im-dec5-web02-ng1 ansible_port=14225
im-dev-dec-doc02-ng1 ansible_port=14225
im-dev-dec5-app01-ng1 ansible_port=14225
im-dev-dec5-elastic01-ng1 ansible_port=14225
im-dev-dec5-mail01-ng1 ansible_port=14225
im-dev-dec5-percona01-ng1 ansible_port=14225
im-dev-dec5-web01-ng1 ansible_port=14225
im-dev-liquidador-percona01-ng1 ansible_port=14225
im-dev-liquidador-web01-ng1 ansible_port=14225
im-dns-iia.imed.lan ansible_port=14225
im-dns-ng.imed.lan ansible_port=14225
im-dns01-iia1 ansible_port=14225
im-dns01-ng1 ansible_port=14225
im-elastic-kibana-pre-iia1 ansible_port=14225
im-elastic-kibana-qa-iia1 ansible_port=14225
im-ent-rundeck01-iia1 ansible_port=14225
im-ent-rundeck01-ng1 ansible_port=14225
im-ftp01-ng1 ansible_port=14225
im-hacias01-iia1 ansible_port=14225
im-hacias01-ng1 ansible_port=14225
im-harundeck-ng1 ansible_port=14225
im-haservice01-ng1 ansible_port=14225
im-jenkins-nacional01-iia1 ansible_port=14225
im-kvm10-ng1 ansible_port=22
im-kvm27-iia1 ansible_port=14225
im-liquidador-ha01-iia1 ansible_port=14225
im-liquidador-ha01-ng1 ansible_port=14225
im-liquidador-ha02-ng1 ansible_port=14225
im-liquidador-percona01-iia1 ansible_port=14225
im-liquidador-redis01-ng1 ansible_port=14225
im-liquidador-web01-iia1 ansible_port=14225
im-liquidador-web01-ng1 ansible_port=14225
im-liquidador-web02-iia1 ansible_port=14225
im-liquidador-web02-ng1 ansible_port=14225
im-liquidador-web03-iia1 ansible_port=14225
im-liquidador-web03-ng1 ansible_port=14225
im-liquidador-web04-iia1 ansible_port=14225
im-liquidador-web04-ng1 ansible_port=14225
im-liquidador-web05-ng1 ansible_port=14225 ansible_user=ansible
im-liquidadorpre-db-iia1 ansible_port=14225
im-liquidadorpre-redis01-ng1 ansible_port=14225
im-liquidadorpre-web01-ng1 ansible_port=14225
im-liquidadorqa-elastic01-iia1 ansible_port=14225
im-liquidadorqa-logger01-iia1 ansible_port=14225
im-liquidadorqa-percona01-iia1 ansible_port=14225
im-liquidadorqa-web01-iia1 ansible_port=14225
im-lme-ha ansible_port=14225
im-lme-ha01-iia1 ansible_port=14225
im-lme-ha01-ng1 ansible_port=14225
im-lme-ha01-php8imed-iia1 ansible_port=14225
im-lme-mysql8 ansible_port=14225
im-lme-mysql8-bd ansible_port=14225
im-lme-mysql8router01-iia1 ansible_port=14225
im-lme-mysql8router01-ng1 ansible_port=14225
im-lme-percona ansible_port=14225
im-lme-percona01-iia1 ansible_port=14225
im-lme-percona01-ng2 ansible_port=14225
im-lme-rancher-master-mysql8-iia1 ansible_port=14225
im-lme-web ansible_port=14225
im-lme-web-php8-iia1 ansible_port=14225
im-lme-web-php8-ng1 ansible_port=14225
im-lme-web01-iia1 ansible_port=14225 ansible_user=ansible
im-lme-web01-ng1 ansible_port=14225 ansible_user=ansible
im-lme-web01-php8imed-iia1 ansible_port=14225
im-lme-web01-php8imed-ng1 ansible_port=14225
im-lme-web02-iia1 ansible_port=14225 ansible_user=ansible
im-lme-web02-ng1 ansible_port=14225 ansible_user=ansible
im-lme-web02-php8imed-iia1 ansible_port=14225
im-lme-web02-php8imed-ng1 ansible_port=14225
im-lme-web03-iia1 ansible_port=14225 ansible_user=ansible
im-lme-web03-ng1 ansible_port=14225 ansible_user=ansible
im-lme-web03-php8imed-iia1 ansible_port=14225
im-lme-web03-php8imed-ng1 ansible_port=14225
im-lme-web04-iia1 ansible_port=14225 ansible_user=ansible
im-lme-web04-ng1 ansible_port=14225 ansible_user=ansible
im-lme-web04-php8imed-iia1 ansible_port=14225
im-lme-web04-php8imed-ng1 ansible_port=14225
im-lme-web05-ng1 ansible_port=14225 ansible_user=ansible
im-lme-web05-php8imed-iia1 ansible_port=14225
im-lme-web05-php8imed-ng1 ansible_port=14225
im-lme-ws ansible_port=14225
im-lme-ws01-iia1 ansible_port=14225
im-lme-ws01-ng1 ansible_port=14225
im-lme-ws02-ng1 ansible_port=14225
im-lmebd-iia1 ansible_port=14225
im-lmebd-iia2 ansible_port=14225
im-lmemysql8-iia1 ansible_port=14225
im-lmemysql8-iia2 ansible_port=14225
im-lmemysql8-ng1 ansible_port=14225
im-lmepre-ha01-ng1 ansible_port=14225
im-lmepre-ha01-php8imed-iia1 ansible_port=14225
im-lmepre-ha02-php8imed-iia1 ansible_port=14225
im-lmepre-percona01-ng1 ansible_port=14225
im-lmepre-rancher-master01-iia1 ansible_port=14225
im-lmepre-web01-ng1 ansible_port=14225
im-lmepre-web01-php8imed-iia1 ansible_port=14225
im-lmepre-web02-ng1 ansible_port=14225
im-lmepre-web02-php8imed-iia1 ansible_port=14225
im-lmepre-ws01-ng1 ansible_port=14225
im-lmepre-ws02-ng1 ansible_port=14225
im-lmepre-ws03-ng1 ansible_port=14225
im-lmeqa-ha01-iia1 ansible_port=14225
im-lmeqa-ha01-ng1 ansible_port=14225
im-lmeqa-percona01-iia1 ansible_port=14225
im-lmeqa-percona02-ng1 ansible_port=14225
im-lmeqa-web01-iia1 ansible_port=14225
im-lmeqa-web01-php8imed-ng1 ansible_port=14225
im-lmeqa-web02-ng1 ansible_port=14225
im-lmeqa-web02-php8imed-ng1 ansible_port=14225
im-lmeqa-web03-ng1 ansible_port=14225
im-lmeqa-web03-php8imed-ng1 ansible_port=14225
im-lmeqa-web04-php8imed-ng1 ansible_port=14225
im-lmeqa-web05-php8imed-ng1 ansible_port=14225
im-lmeqa-web06-php8imed-ng1 ansible_port=14225
im-mail01-iia1 ansible_port=14225
im-mail01-ng1 ansible_port=14225
im-medsign-mongo01-gcp1-iia1 ansible_port=14225
im-medsign-mongo01pre-gcp1-iia1 ansible_port=14225
im-mgpsqa-web01-iia1 ansible_port=14225
im-monetdb01-ng1 ansible_port=14225
im-msgha01-ng1 ansible_port=14225
im-msgmantencion.ng1 ansible_port=14225
im-mysqlrouterqa01-ng1 ansible_port=14225
im-nessus01-ng1 ansible_port=22
im-netbox-ng1 ansible_port=14225
im-pentaho-ng1 ansible_port=14225
im-pentaho02-iia1 ansible_port=14225
im-pivote-pasos-prod-ng1 ansible_port=14225
im-pivote-puppet-prod-iia1 ansible_port=14225
im-poc-commvault02-ng1 ansible_port=14225
im-pre-dec-doc01-ng1 ansible_port=14225
im-pre-dec-doc02-iia1 ansible_port=14225
im-pre-dec-haproxy01-ng1 ansible_port=14225
im-pre-dec-haproxy02-iia1 ansible_port=14225
im-pre-dec5-app01-ng1 ansible_port=14225
im-pre-dec5-app02-iia1 ansible_port=14225
im-pre-dec5-elastic01-ng1 ansible_port=14225
im-pre-dec5-elastic02-iia1 ansible_port=14225
im-pre-dec5-mail01-ng1 ansible_port=14225
im-pre-dec5-mail02-iia1 ansible_port=14225
im-pre-dec5-percona01-ng1 ansible_port=14225
im-pre-dec5-percona02-iia1 ansible_port=14225
im-pre-dec5-web01-ng1 ansible_port=14225
im-pre-dec5-web02-iia1 ansible_port=14225
im-qa-dec-doc02-ng1 ansible_port=14225
im-qa-dec5-app01-ng1 ansible_port=14225
im-qa-dec5-elastic01-ng1 ansible_port=14225
im-qa-dec5-mail01-ng1 ansible_port=14225
im-qa-dec5-percona01-ng1 ansible_port=14225
im-qa-dec5-web01-ng1 ansible_port=14225
im-qbiz-hub01-iia1 ansible_port=14225
im-qbiz-netsuite01-iia1 ansible_port=14225
im-rancher-ha01-ng1 ansible_port=14225
im-rancher-master-mysql1-iia1 ansible_port=14225
im-rancher-master07-ng1 ansible_port=14225
im-rancher-master10-ng1 ansible_port=14225
im-rancher-master11-iia1 ansible_port=14225
im-rancher-master12-iia1 ansible_port=14225
im-rancher-master13-ng1 ansible_port=14225
im-rancher-master14-iia1 ansible_port=14225
im-rancher-master15-iia1 ansible_port=14225
im-rancher-master18-gcp-iia1 ansible_port=14225
im-rancher-master20-iia1 ansible_port=14225
im-rancher-master23-iia1 ansible_port=14225
im-rancher-master24-ng1 ansible_port=14225
im-rancher-master25-ng1 ansible_port=14225
im-rancher-master27-iia1 ansible_port=14225
im-rancher-master28-ng1 ansible_port=14225
im-rancher-master32-ng1 ansible_port=14225
im-rancher-master38-ng1 ansible_port=14225
im-rancher-master39-ng1 ansible_port=14225
im-rancher-master41-ng1 ansible_port=14225
im-rancher-master42-ng1 ansible_port=14225
im-rancher-master44-ng1 ansible_port=14225
im-rancher-master45-ng1 ansible_port=14225
im-rancherdb-iia1 ansible_port=14225
im-repo01-ng1 ansible_port=14225
im-reportesmysql-iia1 ansible_port=14225
im-rmepre-web01-ng1 ansible_port=14225
im-rmepre-web02-ng1 ansible_port=14225
im-rmeqa-percona01-iia1 ansible_port=14225
im-rmeqa-percona01-ng1 ansible_port=14225
im-rmeqa-web01-iia1 ansible_port=14225
im-rmeqa-web01-ng1 ansible_port=14225
im-rundeck-bd1-iia1 ansible_port=14225
im-rundeck-bi-iia1 ansible_port=14225
im-rundeck-bi02-iia1 ansible_port=14225
im-rundeck01-iia1 ansible_port=14225
im-rundeck01-ng1 ansible_port=14225
im-sec-siem01-iia1 ansible_port=14225
im-secbt-jp01-iia1 ansible_port=14225 ansible_python_interpreter=/usr/local/bin/python3.10
im-secbt-jp01-ng1 ansible_port=14225 ansible_python_interpreter=/usr/local/bin/python3.10
im-sftp-klap-ng1 ansible_port=22
im-sftp-mongo01-iia1 ansible_port=14225
im-zabbix01-iia1 ansible_port=14225
im-zabbix01-ng1 ansible_port=14225
poc-im-bono3-md01-ng1 ansible_port=14225
poc-im-bono3-motor01-ng1 ansible_port=14225
poc-im-bono3-motor02-ng1 ansible_port=14225
poc-im-bono3-web01-ng1 ansible_port=14225
poc-im-bono3-web04-ng1 ansible_port=14225
poc-im-ddiscover-ng1 ansible_port=14225
poc-im-dec5-percona01-iia1 ansible_port=14225
poc-im-medsign-mongo01-gcp1-iia1 ansible_port=14225
poc-im-mysql-perf01-iia1 ansible_port=14225
poc-im-mysql-perf01-ng1 ansible_port=14225
poc-im-mysqlmonitor-ng1 ansible_port=14225
poc-im-mysqlrouter-ng1 ansible_port=14225
poc-im-sec-siem01-ng1 ansible_port=14225
[bono_web]
im-bono3-web01-ng1
im-bono3-web02-ng1
im-bono3-web03-ng1
im-bono3-web04-ng1
im-bono3-web05-ng1
im-bono3-web06-ng1
im-bono3-web07-ng1
im-bono3-web08-ng1
im-bono3-web09-ng1
im-bono3-web10-ng1
im-bono3-web11-ng1
im-bono3-web12-ng1
im-bono3-web13-ng1
im-bono3-web14-ng1
im-bono3-web15-ng1

[cme3_web]
im-cme3-web01-ng1
im-cme3-web02-ng1
im-cme3-web03-ng1
im-cme3-web04-ng1
im-cme3-web05-ng1

[lme_web]
im-lme-web01-ng1
im-lme-web02-ng1
